#!/usr/bin/env sh

m='=========================================='

{
  printf "%s\n%s\n%s\n" "$m" "libtoolize --force" "$m"
  libtoolize --force

  printf "\n%s\n%s\n%s\n" "$m" "aclocal" "$m"
  aclocal

  printf "\n%s\n%s\n%s\n" "$m" "autoheader" "$m"
  autoheader

  printf "\n%s\n%s\n%s\n" "$m" "autoconf" "$m"
  autoconf

  printf "\n%s\n%s\n%s\n" "$m" "automake --add-missing" "$m"
  automake --add-missing

  printf "\n%s\n%s\n%s\n" "$m" "./configure" "$m"
  ./configure

} | tee autogen_log
